// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEcommerce.Models
{
    public partial class Product
    {
        public int Id { get; set; }
        public string Productid { get; set; }
        public string Productname { get; set; }
        public int? Quantity { get; set; }
        public double? Price { get; set; }
        public double? Discount { get; set; }
        public int? Category { get; set; }
        public string Image { get; set; }

        public virtual Category CategoryNavigation { get; set; }
    }
}